### ISSUE TITLE
leg_trajectory.cppのループカウンタに浮動小数点型が利用されている

### ISSUE THREAD

**Issue by sakai-waipa** [IRL-Meiji/LIPM_walking_controller_test#1]
leg_trajectory.cppの44行目や62行目に使われている，for文のループカウンタ（今回の場合t）に問題がないか確認してほしいです．
`for(double t=0.0;t<=Tsup;t+=0.001)`
`for(double t=0.0;t<=Tsup;t+=0.001)`

ループカウンタに浮動小数点型を利用すると，情報落ちや丸め誤差による影響を受け，適切に計算できない可能性があります．（今回はあまり関係ないかもしれないけど，直しておいた方がいいかも）
[参考：for文のloop変数にdoubleを使ったらダメの勘違い(+=1.0は問題無いよ)](https://qiita.com/qiitamatumoto/items/0768bfb81f46731971ba)

ループカウンタには整数値を利用して，for文内で除算を行い適切な時刻に変換する方がよいかと思います．
少し考えてみてください！

**Comment by Yoshihiro-Satake** [comment]
csvファイルを見たら大丈夫そうですが、最終的には直すようにします

**Comment by sakai-waipa** [comment]
了解です！
直したらpullしてcloseしてください．

**Comment by Yoshihiro-Satake** [comment]
全て修正してpushしました

**Comment by sakai-waipa** [comment]
お疲れ様です！
問題なければこのissueをcloseしましょう！
（右下の「Close with comment」でcloseできます）
